modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPL v3"

[[mods]]
logoFile="logo.png"
modId="lockout"
version="1.0"
displayName="Blockout"
authors="vincor-qc (Vincent)"
description='''
A simple lockout minigame mod
'''
displayURL="https://github.com/vincor-qc/blockout"

[[dependencies.lockout]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lockout]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
